# Generated by Django 5.1.6 on 2025-05-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0002_rename_username_profile_display_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
    ]
