# Generated by Django 5.1.6 on 2025-05-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="username",
            new_name="display_name",
        ),
    ]
