# Generated by Django 5.2.1 on 2025-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
