# Generated by Django 5.2.1 on 2025-05-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(null=True, upload_to="merchstore/"),
        ),
    ]
