# Generated by Django 5.2.1 on 2025-05-17 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
