# Generated by Django 5.2.1 on 2025-05-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0004_transaction_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("CRT", "On Cart"),
                    ("PAY", "To Pay"),
                    ("SHP", "To Ship"),
                    ("RCV", "To Receive"),
                ],
                default="CRT",
                max_length=3,
            ),
        ),
    ]
