# Generated by Django 5.2.1 on 2025-05-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("merchstore", "0005_alter_transaction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="merchstore/"),
        ),
    ]
