# Generated by Django 5.1.6 on 2025-05-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_article_author_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
